config/routes.rb
Rails.application.routes.draw do
  resources :r_reports
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: redirect("/r_reports") 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/r_report.rb
class RReport < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/r_reports_controller.rb
class RReportsController < ApplicationController
  before_action :set_r_report, only: %i[ show edit update destroy ]

  # GET /r_reports or /r_reports.json
  def index
    @r_reports = RReport.all
  end

  # GET /r_reports/1 or /r_reports/1.json
  def show
  end

  # GET /r_reports/new
  def new
    @r_report = RReport.new
  end

  # GET /r_reports/1/edit
  def edit
  end

  # POST /r_reports or /r_reports.json
  def create
    @r_report = RReport.new(r_report_params)

    respond_to do |format|
      if @r_report.save
        format.html { redirect_to r_report_url(@r_report), notice: "R report was successfully created." }
        format.json { render :show, status: :created, location: @r_report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @r_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /r_reports/1 or /r_reports/1.json
  def update
    respond_to do |format|
      if @r_report.update(r_report_params)
        format.html { redirect_to r_report_url(@r_report), notice: "R report was successfully updated." }
        format.json { render :show, status: :ok, location: @r_report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @r_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /r_reports/1 or /r_reports/1.json
  def destroy
    @r_report.destroy!

    respond_to do |format|
      format.html { redirect_to r_reports_url, notice: "R report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_r_report
      @r_report = RReport.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def r_report_params
      params.require(:r_report).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/r_reports_helper.rb
module RReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Report</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script>
      $(document).ready(function() {
        $(".sample_select").select2({
          width: 600,
          multiple: true
        });
      });
    </script>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/r_reports/_form.html.erb
<%= form_with(model: r_report, class: "contents") do |form| %>
  <% if r_report.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(r_report.errors.count, "error") %> prohibited this r_report from being saved:</h2>

      <ul>
        <% r_report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.select :content, ["rails1", "rails2", "rails3", "custom"], { prompt: "-- 選択してください --" }, { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", id: "content-select" } %>
    <%= form.text_field :custom_content, { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "-- 自由に入力してください --", id: "custom-content-field", style: "display: none;" } %>
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      const selectField = document.getElementById('content-select');
      const customField = document.getElementById('custom-content-field');

      selectField.addEventListener('change', function() {
        if (selectField.value === 'custom') {
          customField.style.display = 'block';
        } else {
          customField.style.display = 'none';
        }
      });
    });
  </script>

  <div class="my-5">
    <%= form.label :time %>
    <%= form.number_field :time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :credo %>
    <%= form.select :credo, ["ヤクルト", "ああああああ", "毎週提出"], {}, { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/r_reports/_r_report.html.erb
<div id="<%= dom_id r_report %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= r_report.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= r_report.content %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this r report", r_report, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this r report", edit_r_report_path(r_report), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/r_reports/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing r report</h1>

  <%= render "form", r_report: @r_report %>

  <%= link_to "Show this r report", @r_report, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to r reports", r_reports_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/r_reports/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">R reports</h1>
    <%= link_to "New r report", new_r_report_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="r_reports" class="min-w-full">
    <%= render @r_reports %>
  </div>
</div>

app/views/r_reports/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New r report</h1>

  <%= render "form", r_report: @r_report %>

  <%= link_to "Back to r reports", r_reports_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/r_reports/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @r_report %>

    <%= link_to "Edit this r_report", edit_r_report_path(@r_report), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this r_report", r_report_path(@r_report), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to r_reports", r_reports_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>